/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.12.2.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as actions_uploadFile from "../actions/uploadFile";
import type * as countTasks from "../countTasks";
import type * as createTask from "../createTask";
import type * as crons from "../crons";
import type * as deleteFile from "../deleteFile";
import type * as getSafeFiles from "../getSafeFiles";
import type * as getTask from "../getTask";
import type * as internal from "../internal";
import type * as listTasks from "../listTasks";
import type * as listUsers from "../listUsers";
import type * as resetData from "../resetData";
import type * as saveComment from "../saveComment";
import type * as saveUser from "../saveUser";
import type * as updateTask from "../updateTask";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  "actions/uploadFile": typeof actions_uploadFile;
  countTasks: typeof countTasks;
  createTask: typeof createTask;
  crons: typeof crons;
  deleteFile: typeof deleteFile;
  getSafeFiles: typeof getSafeFiles;
  getTask: typeof getTask;
  internal: typeof internal;
  listTasks: typeof listTasks;
  listUsers: typeof listUsers;
  resetData: typeof resetData;
  saveComment: typeof saveComment;
  saveUser: typeof saveUser;
  updateTask: typeof updateTask;
}>;
