/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.0.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as comments from "../comments";
import type * as crons from "../crons";
import type * as data from "../data";
import type * as files from "../files";
import type * as internal_ from "../internal";
import type * as tasks from "../tasks";
import type * as users from "../users";
import type * as util from "../util";
import type * as validators from "../validators";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  comments: typeof comments;
  crons: typeof crons;
  data: typeof data;
  files: typeof files;
  internal: typeof internal_;
  tasks: typeof tasks;
  users: typeof users;
  util: typeof util;
  validators: typeof validators;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
